AgiCredAju79/AgiCredAju79/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace AgiCredAju79.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CadastrosPendentes()
        {
            return View();
        }
    }
}

AgiCredAju79/AgiCredAju79/Controllers/NotaEmprestimoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgiCredAju79.Models;
using AgiCredAju79.Repositories.Contexts;
using AgiCredAju79.Repositories.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Drawing;

namespace AgiCredAju79.Controllers
{
    public class NotaEmprestimoesController : Controller
    {
        private readonly DbContextMariaDB _context;

    
        public NotaEmprestimoesController(DbContextMariaDB context)
        {
            _context = context;
        }

        // GET: NotaEmprestimoes
        public async Task<IActionResult> Index()
        {
            string? login = Convert.ToString(HttpContext.Session.GetString("KEY-EEW-55D"));
            if (login != "true")
            {
                return Redirect("../Login");
            }

            return View(await _context.NotaEmprestimo.Where(e => e.Categoria == "EmDia").ToListAsync());
        }

        public async Task<IActionResult> NaoPagos()
        {
            string? login = Convert.ToString(HttpContext.Session.GetString("KEY-EEW-55D"));
            if (login != "true")
            {
                return Redirect("../Login");
            }

            return View(await _context.NotaEmprestimo.Where(e => e.Categoria == "NaoPago").ToListAsync());
        }
        
        public async Task<IActionResult> PromessasPAG()
        {
            string? login = Convert.ToString(HttpContext.Session.GetString("KEY-EEW-55D"));
            if (login != "true")
            {
                return Redirect("../Login");
            }

            return View(await _context.NotaEmprestimo.Where(e => e.Categoria == "PromessaPAG").ToListAsync());
        }

        public async Task<IActionResult> Perdidos()
        {
            string? login = Convert.ToString(HttpContext.Session.GetString("KEY-EEW-55D"));
            if (login != "true")
            {
                return Redirect("../Login");
            }

            return View(await _context.NotaEmprestimo.Where(e => e.Categoria == "Perdido").ToListAsync());
        }

        // GET: NotaEmprestimoes/Create
        public IActionResult Create()
        {
            string? login = Convert.ToString(HttpContext.Session.GetString("KEY-EEW-55D"));
            if (login != "true")
            {
                return Redirect("../Login");
            }

            return View();
        }

        // POST: NotaEmprestimoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Categoria,DataDoAcordo,Nome, CPF,Celular,Indicacao,TipoDeEmprestimo,DataDoPagamento,ValorDoEmprestimo,JuroMensalPorcentagem,Armotizado,JurosPagosTotal,ListaParcelasPagas,DataDoUltimoPagamento,DataDePromessaDePagamento,Observacao")] NotaEmprestimo notaEmprestimo)
        {
            string? login = Convert.ToString(HttpContext.Session.GetString("KEY-EEW-55D"));
            if (login != "true")
            {
                return Redirect("../Login");
            }

            if (ModelState.IsValid)
            {
                notaEmprestimo.Categoria = "EmDia";
                _context.Add(notaEmprestimo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(notaEmprestimo);
        }

        // GET: NotaEmprestimoes/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            string? login = Convert.ToString(HttpContext.Session.GetString("KEY-EEW-55D"));
            if (login != "true")
            {
                //return Redirect("../Login");
            }

            if (id == null)
            {
                return NotFound();
            }

            var notaEmprestimo = await _context.NotaEmprestimo.FindAsync(id);
            if (notaEmprestimo == null)
            {
                return NotFound();
            }

            decimal? valorEmAberto = notaEmprestimo.ValorDoEmprestimo - notaEmprestimo.Armotizado;
            ViewBag.valorEmAberto = valorEmAberto;

            ViewBag.valorAPagarHoje = (valorEmAberto * notaEmprestimo.JuroMensalPorcentagem) / 100;

            return View(notaEmprestimo);
        }

        // POST: NotaEmprestimoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, decimal? valorPago, [Bind("Id,Categoria,DataDoAcordo,Nome, CPF,Celular,Indicacao,TipoDeEmprestimo,DataDoPagamento,ValorDoEmprestimo,DataDoEmprestimo,JuroMensalPorcentagem,Armotizado,JurosPagosTotal,ListaParcelasPagas,DataDoUltimoPagamento,DataDePromessaDePagamento,Observacao")] NotaEmprestimo notaEmprestimo)
        {
            string? login = Convert.ToString(HttpContext.Session.GetString("KEY-EEW-55D"));
            if (login != "true")
            {
                return Redirect("../Login");
            }

            if (id != notaEmprestimo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (valorPago >= 0.01m)
                    {
                        decimal? valorEmAberto = notaEmprestimo.ValorDoEmprestimo - notaEmprestimo.Armotizado;
                        decimal? valorAPagarHoje = (valorEmAberto * notaEmprestimo.JuroMensalPorcentagem) / 100;

                        if (valorPago > valorAPagarHoje)
                        {
                            decimal? diferenca = valorPago - valorAPagarHoje;
                            notaEmprestimo.Armotizado += diferenca ?? notaEmprestimo.Armotizado;
                        }
                        notaEmprestimo.JurosPagosTotal += valorPago ?? notaEmprestimo.JurosPagosTotal;
                    }

                    _context.Update(notaEmprestimo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotaEmprestimoExists(notaEmprestimo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (notaEmprestimo.Categoria == "NaoPago") return RedirectToAction("NaoPagos");
                if (notaEmprestimo.Categoria == "PromessaPAG") return RedirectToAction("PromessasPAG");
                if (notaEmprestimo.Categoria == "Perdido") return RedirectToAction("Perdidos");
                return RedirectToAction(nameof(Index));
            }
            return View(notaEmprestimo);
        }

        private bool NotaEmprestimoExists(long id)
        {
            return _context.NotaEmprestimo.Any(e => e.Id == id);
        }
    }
}

AgiCredAju79/AgiCredAju79/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>AgiCredAju79</title>

    <!-- Custom fonts for this template-->
    <link href="~/lib/sb-admin-2/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/lib/sb-admin-2/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/sb-admin-2/vendor/jquery/jquery.min.js"></script>
    <script src="~/lib/sb-admin-2/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
                <div class="col-auto">
                    <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                </div>
                <div class="sidebar-brand-text mx-3">AgiCredAju<sup>79</sup></div>
            </a>

            <!--
            <hr class="sidebar-divider my-0">
            Nav Item - Dashboard 
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            -->

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Empréstimos
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                   aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Notas</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Opções</h6>
                        <a class="collapse-item" asp-area="" asp-controller="NotaEmprestimoes" asp-action="Index">Em Dias</a>
                        <a class="collapse-item" asp-area="" asp-controller="NotaEmprestimoes" asp-action="NaoPagos">Não Pagos</a>
                        <a class="collapse-item" asp-area="" asp-controller="NotaEmprestimoes" asp-action="PromessasPAG">Promessas PAG</a>
                        <a class="collapse-item" asp-area="" asp-controller="NotaEmprestimoes" asp-action="Perdidos">Perdidos</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!--
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="CadastrosPendentes">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Cadastros Pendentes</span>
                </a>
            </li>

            <hr class="sidebar-divider d-none d-md-block">
            -->

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                   aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>


                    <!-- data e hora do sistema
                    <div class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <div class="btn btn-secondary btn-icon-split">
                                <span class="icon text-white-50">
                                    <i class="fas fa-arrow-right"></i>
                                </span>
                                <span class="text">@DateTime.Now.ToString("dd/MM/yyyy HH:mm tt")</span>
                            </div>
                        </div>
                    </div>
                    -->



              

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                   

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">User</span>
                                <img class="img-profile rounded-circle"
                                     src="~/imgs/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    @RenderBody()

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Deseja Sair?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="./Login/Logout">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Core plugin JavaScript-->
    <script src="~/lib/sb-admin-2/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/lib/sb-admin-2/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/lib/sb-admin-2/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/lib/sb-admin-2/js/demo/chart-area-demo.js"></script>
    <script src="~/lib/sb-admin-2/js/demo/chart-pie-demo.js"></script>

    @RenderSection("Scripts", required: false)
</body>

</html>